<?php

namespace App\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property int $id
 * @property int $agency_id
 * @property int $user_id
 * @property User $_user_id
 * @property Agency $_agency_id
 */
class AgencyUser extends Model
{

    #[Generated]
    public static function table(): string
    {
        return 'agency_user';
    }

    #[Generated]
    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->nullable()->hasDefault(true),
            'agency_id' => (new ModelField('agency_id'))->type('INTEGER')->notNull()->hasDefault(false)->references(Agency::class,'id'),
            'user_id' => (new ModelField('user_id'))->type('INTEGER')->notNull()->hasDefault(false)->references(User::class,'id')
        ];
    }

    #[Generated]
    public function _user_id(): HasOne
    {
        return $this->hasOne('_user_id', 'user_id', User::class, 'id');
    }

    #[Generated]
    public function _agency_id(): HasOne
    {
        return $this->hasOne('_agency_id', 'agency_id', Agency::class, 'id');
    }

    #[Generated]
    public static function relations(): array
    {
        return [
            "_user_id",
            "_agency_id",
        ];
    }

}