<?php

namespace App\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property int $id
 * @property string $name
 * @property AgencyUser[] $users
 */
class Agency extends Model
{

    #[Generated]
    public static function table(): string
    {
        return 'agency';
    }

    #[Generated]
    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->nullable()->hasDefault(true),
            'name' => (new ModelField('name'))->type('STRING')->notNull()->hasDefault(false)
        ];
    }

    #[Generated]
    public function users(): HasMany
    {
        return $this->hasMany('users', AgencyUser::class, 'agency_id', 'id');
    }

    #[Generated]
    public static function relations(): array
    {
        return [
            "users",
        ];
    }

}