<?php

namespace App\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property int $id
 * @property string $created_at
 * @property string $name
 * @property string $price_dollar
 * @property ProductManager[] $managers
 */
class Product extends Model
{
    use ModelTrait;

    #[Generated]
    public static function table(): string
    {
        return 'product';
    }

    #[Generated]
    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->nullable()->hasDefault(true),
            'created_at' => (new ModelField('created_at'))->type('TIMESTAMP')->nullable()->hasDefault(true),
            'name' => (new ModelField('name'))->type('STRING')->notNull()->hasDefault(false),
            'price_dollar' => (new ModelField('price_dollar'))->type('DECIMAL')->nullable()->hasDefault(true)
        ];
    }

    #[Generated]
    public function managers(): HasMany
    {
        return $this->hasMany('managers', ProductManager::class, 'product', 'id');
    }

    #[Generated]
    public static function relations(): array
    {
        return [
            "managers",
        ];
    }

    public function getPriceWithTax(float $taxRate=0.2): float {
        return $this->price_dollar * (1 + $taxRate);
    }
}