<?php

namespace App\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property int $some_id
 * @property InexistantTable $_some_id
 */
class ShouldNotBeCreated extends Model
{
    #[Generated]
    public static function table(): string
    {
        return 'should_not_be_created';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'some_id' => (new ModelField('some_id'))->type('INTEGER')->nullable()->hasDefault(true)->references(InexistantTable::class,'id')
        ];
    }

    #[Generated]
    public function _some_id(): HasOne
    {
        return $this->hasOne('_some_id', 'some_id', InexistantTable::class, 'id');
    }

    #[Generated]
    public static function relations(): array
    {
        return [
            "_some_id",
        ];
    }

}