<?php

namespace App\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property int $id
 * @property string $login
 * @property string $password
 * @property int $type
 * @property UserType $_type
 * @property ModuleUser[] $modules
 */
class User extends Model
{
    #[Generated]
    public static function table(): string
    {
        return 'user';
    }

    #[Generated]
    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->autoIncrement()->notNull()->hasDefault(true),
            'login' => (new ModelField('login'))->type('STRING')->notNull()->hasDefault(false),
            'password' => (new ModelField('password'))->type('STRING')->notNull()->hasDefault(false),
            'type' => (new ModelField('type'))->type('INTEGER')->nullable()->hasDefault(true)->references(UserType::class,'id')
        ];
    }

    #[Generated]
    public function _type(): HasOne
    {
        return $this->hasOne('_type', 'type', UserType::class, 'id');
    }

    #[Generated]
    public function modules(): HasMany
    {
        return $this->hasMany('modules', ModuleUser::class, 'user', 'id');
    }

    #[Generated]
    public static function relations(): array
    {
        return [
            "modules",
            "_type",
        ];
    }

}