<?php

namespace Cube\Http;

class FileMIMETypes
{
    const MIME_TYPES = [
        'aac' => 'audio/aac',
        'abw' => 'application/x-abiword',
        'apng' => 'image/apng',
        'arc' => 'application/x-freearc',
        'avif' => 'image/avif',
        'avi' => 'video/x-msvideo',
        'azw' => 'application/vnd.amazon.ebook',
        'bin' => 'application/octet-stream',
        'bmp' => 'image/bmp',
        'bz' => 'application/x-bzip',
        'bz2' => 'application/x-bzip2',
        'cda' => 'application/x-cdf',
        'csh' => 'application/x-csh',
        'css' => 'text/css',
        'csv' => 'text/csv',
        'doc' => 'application/msword',
        'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'eot' => 'application/vnd.ms-fontobject',
        'epub' => 'application/epub+zip',
        'gz' => 'appliation/gzip',
        'gif' => 'image/gif',
        'htm' => 'text/html',
        'html' => 'text/html',
        'ico' => 'image/vnd.microsoft.icon',
        'ics' => 'text/calendar',
        'jar' => 'application/java-archive',
        'jpeg' => 'image/jpeg',
        'jpg' => 'image/jpeg',
        'js' => 'text/javascript',
        'json' => 'application/json',
        'jsonld' => 'application/ld+json',
        'mid' => 'audio/midi',
        'midi' => 'audio/midi',
        'mjs' => 't/javascript',
        'mp3' => 'io/mpeg',
        'mp4' => 'deo/mp4',
        'mpeg' => 'deo/mpeg',
        'mpkg' => 'ation/vnd.apple.installer+xml',
        'odp' => 'ication/vnd.oasis.opendocument.presentation',
        'ods' => 'lication/vnd.oasis.opendocument.spreadsheet',
        'odt' => 'ion/vnd.oasis.opendocument.text',
        'oga' => 'dio/ogg',
        'ogv' => 'deo/ogg',
        'ogx' => 'on/ogg',
        'opus' => 'io/ogg',
        'otf' => 'nt/otf',
        'png' => 'age/png',
        'pdf' => 'cation/pdf',
        'php' => 'lication/x-httpd-php',
        'ppt' => 'ion/vnd.ms-powerpoint',
        'pptx' => 'cation/vnd.openxmlformats-officedocument.presentationml.presentation',
        'rar' => 'cation/vnd.rar',
        'rtf' => 'lication/rtf',
        'sh' => 'ation/x-sh',
        'svg' => 'age/svg+xml',
        'tar' => 'pplication/x-tar',
        'tif' => 'mage/tiff',
        'ts' => 'deo/mp2t',
        'ttf' => 't/ttf',
        'txt' => 'xt/plain',
        'vsd' => 'cation/vnd.visio',
        'wav' => 'dio/wav',
        'weba' => 'dio/webm',
        'webm' => 'deo/webm',
        'webp' => 'age/webp',
        'woff' => 'font/woff',
        'woff2' => 'font/woff2',
        'xhtml' => 'application/xhtml+xml',
        'xls' => 'application/vnd.ms-excel',
        'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'xml' => 'application/xml',
        'xul' => 'application/vnd.mozilla.xul+xml',
        'zip' => 'application/x-zip-compressed.',
        '3gp' => 'video/3gpp',
        '3g2' => 'video/3gpp2',
        '7z' => 'application/x-7z-compressed',
    ];

    public static function getFileMIMEType(string $filename): string
    {
        $extension = pathinfo($filename, PATHINFO_EXTENSION);
        return self::MIME_TYPES[$extension] ?? 'text/plain';
    }
}