<?php

namespace Cube\Tests\Units\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table` (2025-02-23 21:07:42).
 *
 * @property int    $id
 * @property string $name
 * @property string $created_at
 */
class __cubeMigration extends Model
{
    public static function table(): string
    {
        return '__cube_migration';
    }

    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->autoIncrement()->nullable(false)->hasDefault(true),
            'name' => (new ModelField('name'))->type('STRING')->nullable(false)->hasDefault(false),
            'created_at' => (new ModelField('created_at'))->type('TIMESTAMP')->nullable(true)->hasDefault(true),
        ];
    }

    public static function relations(): array
    {
        return [
        ];
    }
}
