<?php

namespace Cube\Tests\Units\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property int $id
 * @property string $label
 * @property ModuleUser[] $users
 */
class Module extends Model
{
    #[Generated]
    public static function table(): string
    {
        return 'module';
    }

    #[Generated]
    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->autoIncrement()->nullable(false)->hasDefault(true),
            'label' => (new ModelField('label'))->type('STRING')->nullable(false)->hasDefault(false)
        ];
    }

    #[Generated]
    public function users(): HasMany
    {
        return $this->hasMany('users', ModuleUser::class, 'module', 'id');
    }

    #[Generated]
    public static function relations(): array
    {
        return [
            "users",
        ];
    }

}