<?php

namespace Cube\Tests\Units\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table` (2025-02-23 21:38:56).
 *
 * @property int          $id
 * @property string       $label
 * @property ModuleUser[] $users
 */
class Module extends Model
{
    public static function table(): string
    {
        return 'module';
    }

    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->autoIncrement()->nullable(false)->hasDefault(true),
            'label' => (new ModelField('label'))->type('STRING')->nullable(false)->hasDefault(false),
        ];
    }

    public function users(): HasMany
    {
        return $this->hasMany(ModuleUser::class, 'module', 'id');
    }

    public static function relations(): array
    {
        return [
            'users',
        ];
    }
}
