<?php

namespace Cube\Tests\Units\Models;

use Cube\Models\Model;
use Cube\Models\ModelField;
use Cube\Models\Relations\HasMany;
use Cube\Models\Relations\HasOne;

/**
 * Generated by `Cube\Models\ModelGenerator\Table` (2025-02-23 21:38:56)
 * @property int $user
 * @property int $module
 * @property Module $module
 * @property User $user
 */
class ModuleUser extends Model
{
    public static function table(): string
    {
        return 'module_user';
    }

    /**
     * @return array<string,ModelField>
     */
    public static function fields(): array
    {
        return [
            'user' => (new ModelField('user'))->type('INTEGER')->nullable(false)->hasDefault(false)->references(User::class,'id'),
            'module' => (new ModelField('module'))->type('INTEGER')->nullable(false)->hasDefault(false)->references(Module::class,'id')
        ];
    }

    public function module(): HasOne
    {
        return $this->hasOne('module', Module::class, 'id');
    }

    public function user(): HasOne
    {
        return $this->hasOne('user', User::class, 'id');
    }

    public static function relations(): array
    {
        return [
            "module",
"user",
        ];
    }
}