<?php

namespace Cube\Tests\Units\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property int $user
 * @property int $module
 * @property Module $_module
 * @property User $_user
 */
class ModuleUser extends Model
{
    #[Generated]
    public static function table(): string
    {
        return 'module_user';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'user' => (new ModelField('user'))->type('INTEGER')->notNull()->hasDefault(false)->references(User::class,'id'),
            'module' => (new ModelField('module'))->type('INTEGER')->notNull()->hasDefault(false)->references(Module::class,'id')
        ];
    }

    #[Generated]
    public function _module(): HasOne
    {
        return $this->hasOne('_module', 'module', Module::class, 'id');
    }

    #[Generated]
    public function _user(): HasOne
    {
        return $this->hasOne('_user', 'user', User::class, 'id');
    }

    #[Generated]
    public static function relations(): array
    {
        return [
            "_module",
            "_user",
        ];
    }

}