<?php

namespace Cube\Tests\Units\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property int $product
 * @property string $manager
 * @property Product $_product
 */
class ProductManager extends Model
{
    #[Generated]
    public static function table(): string
    {
        return 'product_manager';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'product' => (new ModelField('product'))->type('INTEGER')->notNull()->hasDefault(false)->references(Product::class,'id'),
            'manager' => (new ModelField('manager'))->type('STRING')->notNull()->hasDefault(false)
        ];
    }

    #[Generated]
    public function _product(): HasOne
    {
        return $this->hasOne('_product', 'product', Product::class, 'id');
    }

    #[Generated]
    public static function relations(): array
    {
        return [
            "_product",
        ];
    }

}