<?php

namespace Cube\Tests\Units\Models;

use Cube\Models\Model;
use Cube\Models\ModelField;
use Cube\Models\Relations\HasMany;
use Cube\Models\Relations\HasOne;

/**
 * Generated by `Cube\Models\ModelGenerator\Table` (2025-02-22 12:47:56)
 * @property int $id
 * @property string $created_at
 * @property string $name
 * @property string $price_dollar
 * @property Product[] $products
 */
class Product extends Model
{
    public static function table(): string
    {
        return 'product';
    }

    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->nullable(true)->hasDefault(true),
            'created_at' => (new ModelField('created_at'))->type('TIMESTAMP')->nullable(true)->hasDefault(true),
            'name' => (new ModelField('name'))->type('STRING')->nullable(false)->hasDefault(true),
            'price_dollar' => (new ModelField('price_dollar'))->type('DECIMAL')->nullable(true)->hasDefault(true)
        ];
    }

    public function managers(): HasMany
    {
        return $this->hasMany(ProductManager::class, 'product', 'id');
    }

    public static function relations(): array
    {
        return [
            "managers",
        ];
    }
}