<?php

namespace Cube\Tests\Units\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasOne;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table` (2025-02-23 21:38:56).
 *
 * @property int     $product
 * @property string  $manager
 * @property Product $product
 */
class ProductManager extends Model
{
    public static function table(): string
    {
        return 'product_manager';
    }

    /**
     * @return array<string,ModelField>
     */
    public static function fields(): array
    {
        return [
            'product' => (new ModelField('product'))->type('INTEGER')->nullable(false)->hasDefault(false)->references(Product::class, 'id'),
            'manager' => (new ModelField('manager'))->type('STRING')->nullable(false)->hasDefault(false),
        ];
    }

    public function product(): HasOne
    {
        return $this->hasOne('product', Product::class, 'id');
    }

    public static function relations(): array
    {
        return [
            'product',
        ];
    }
}
