<?php

namespace Cube\Tests\Units\Models;

use Cube\Models\Model;
use Cube\Models\ModelField;
use Cube\Models\Relations\HasMany;
use Cube\Models\Relations\HasOne;

/**
 * Generated by `Cube\Models\ModelGenerator\Table` (2025-02-23 21:38:56)
 * @property int $id
 * @property string $label
 * @property User[] $users
 */
class UserType extends Model
{
    public static function table(): string
    {
        return 'user_type';
    }

    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->autoIncrement()->nullable(false)->hasDefault(true),
            'label' => (new ModelField('label'))->type('STRING')->nullable(false)->hasDefault(false)
        ];
    }

    public function users(): HasMany
    {
        return $this->hasMany(User::class, 'type', 'id');
    }

    public static function relations(): array
    {
        return [
            "users",
        ];
    }
}