<?php

namespace Cube\Tests\Units\Models;

use Cube\Models\Model;
use Cube\Models\ModelField;
use Cube\Models\Relations\HasMany;
use Cube\Models\Relations\HasOne;

/**
 * Generated by `Cube\Models\ModelGenerator\Table` (2025-02-22 12:47:56)
 * @property int $id
 * @property string $login
 * @property string $password
 * @property int $type
 * @property UserType $usertype
 * @property User[] $users
 */
class User extends Model
{
    public static function table(): string
    {
        return 'user';
    }

    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->autoIncrement()->nullable(false)->hasDefault(true),
            'login' => (new ModelField('login'))->type('STRING')->nullable(false)->hasDefault(false),
            'password' => (new ModelField('password'))->type('STRING')->nullable(false)->hasDefault(false),
            'type' => (new ModelField('type'))->type('INTEGER')->nullable(false)->hasDefault(false)->references(UserType::class,'id')
        ];
    }

    public function usertype(): HasOne
    {
        return $this->hasOne('type', UserType::class, 'id');
    }

    public function modules(): HasMany
    {
        return $this->hasMany(ModuleUser::class, 'user', 'id');
    }

    public static function relations(): array
    {
        return [
            "usertype",
"modules",
        ];
    }
}